/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class one_one_Test */

#ifndef _Included_one_one_Test
#define _Included_one_one_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     one_one_Test
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_one_one_Test_sayHello
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
