/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mmotiy_service_Mouse */

#ifndef _Included_com_mmotiy_service_Mouse
#define _Included_com_mmotiy_service_Mouse
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mmotiy_service_Mouse
 * Method:    sendInput
 * Signature: (Lcom/mmotiy/dto/TagINPUT;)V
 */
JNIEXPORT void JNICALL Java_com_mmotiy_service_Mouse_sendInput
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
